---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/ansible:3
    commands:
      - ansible-galaxy collection build
      - ansible-galaxy collection publish --token $${GALAXY_TOKEN} nemunaire-happydomain-${DRONE_TAG##v}.tar.gz
    environment:
      GALAXY_TOKEN:
        from_secret: galaxy-token

trigger:
  event:
    - tag
